### ISSUE TITLE
Shuffleboard Dashboard

### ISSUE THREAD

**Issue by 3LucasZ** [Team3256/FRC_Programming_2024#104]
Should be similar style to last years. Look at FRC Programming 2023 for inspiration.

- [x] Constant to enable/disable
- [x] Driver page
   - [ ] Arm
      - [ ] Current Arm Command
      - [ ] Arm angle
   - [x] Intake
      - [x] Current Intake Command
      - [x] Intake Voltage
   - [x] Shooter
      - [x] Current shooter command
      - [x] Shooter RPM
      - [ ] Feeder RPM
   - [x] Intake
      - [x] Current intake command
      - [x] Beam status
      - [x] Intake RPM
   - [x] Swerve
      - [x] Current swerve command
   - [ ] Climb
      - [ ] Current climb command
      - [ ] Left climb height
      - [ ] Right climb height
- [ ] Electrical page
   - [ ] CAN status of every CAN device
   - [ ] Current drawn on every motor
   - [ ] Voltage supplied on every motor

**Comment by ChaoticChaosTheGreat** [comment]
Climb and arm is not in main, feeder motor has not yet been implemented

**Comment by 3LucasZ** [comment]
Ok. Great work so far.
