### ISSUE TITLE
SimGUI Layout

### ISSUE THREAD

**Issue by 3LucasZ** [Team3256/FRC_Programming_2024#106]
*MAC KEYBOARD LAYOUT*
Keyboard settings MUST be created on a mac
- [ ] Controller + Keyboard 0
   - [ ] w, s Axis 0
   - [ ] a, d Axis 1
   - [ ] q, nothing Axis 2
   - [ ] e, nothing Axis 3
   - [ ] 1: 0*, 2: 90*, 3: 180*, 4: 270* POV
   - [ ] left shift, z, x, c, v, b 
- [ ] Controller + Keyboard 1
   - [ ] i, k Axis 0
   - [ ] j, l Axis 1
   - [ ] u, nothing Axis 2
   - [ ] o, nothing Axis 3
   - [ ] 5: 0*, 6: 90*, 7: 180*, 8: 270* POV
   - [ ] n, m, ,, ., /, right shift
- [ ] Controller + Keyboard 0
   - [ ] nothing, nothing Axis 0
   - [ ] nothing, nothing Axis 1
   - [ ] -, nothing Axis 2
   - [ ] +, nothing Axis 3
   - [ ] arrow up: 0*, arrow right: 90*, arrow down: 180*, arrow left: 270* POV
   - [ ] control, left option, left command, spacebar, right command, right option

*WINDOWS KEYBOARD LAYOUT*
Keyboard settings MUST be created on a windows
- [ ] Controller + Keyboard 0
   - [ ] w, s Axis 0
   - [ ] a, d Axis 1
   - [ ] q, nothing Axis 2
   - [ ] e, nothing Axis 3
   - [ ] 1: 0*, 2: 90*, 3: 180*, 4: 270* POV
   - [ ] left shift, z, x, c, v, b 
- [ ] Controller + Keyboard 1
   - [ ] i, k Axis 0
   - [ ] j, l Axis 1
   - [ ] u, nothing Axis 2
   - [ ] o, nothing Axis 3
   - [ ] 5: 0*, 6: 90*, 7: 180*, 8: 270* POV
   - [ ] n, m, ,, ., /, right shift
- [ ] Controller + Keyboard 0
   - [ ] nothing, nothing Axis 0
   - [ ] nothing, nothing Axis 1
   - [ ] -, nothing Axis 2
   - [ ] +, nothing Axis 3
   - [ ] arrow up: 0*, arrow right: 90*, arrow down: 180*, arrow left: 270* POV
   - [ ] IDK i have not used windows before but assign some 6 consecutive convenient buttons here!

**Comment by realjoshuau** [comment]
superseded by advscope
