### ISSUE TITLE
Current Spike Subsystem Base

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/FRC_Programming_2024#117]
Write a helper function that monitors current and sees if the current is **spiking**

You'll need to write a function that takes past current and current current and see if the current has increased rapidly (di/dt)

**Comment by ChaoticChaosTheGreat** [comment]
Timed boolean works good

**Comment by realjoshuau** [comment]
the point of this was to detect spikes, not just general increases; but timed boolean does work well enough
