### ISSUE TITLE
BetaBot: Swerve PID Tuning & SysID

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/FRC_Programming_2024#118]
Tune the PID for the swerve modules.
Implement SysID
https://docs.wpilib.org/en/stable/docs/software/advanced-controls/system-identification/creating-routine.html
https://www.chiefdelphi.com/t/sysid-with-ctre-swerve-characterization/452631/4

**Comment by ChaoticChaosTheGreat** [comment]
SysID is not supported for swerve according to the docs.

**Comment by realjoshuau** [comment]
It can, docs are just not updated yet.
