### ISSUE TITLE
Intake Rework

### ISSUE THREAD

**Issue by 3LucasZ** [Team3256/FRC_Programming_2024#121]
Rework intake to stop when function blocked() returns true instead of relying on beam break/TOF sensor. "Blocked" function is not implemented yet (it's basically detect current spike task that will be done by someone else) but you can complete this task either before or after blocked is implemented.

**Comment by realjoshuau** [comment]
*Using blocked might not work: the intake motor will use more current but the encoder will still move since the motor will not stall. Use current **limits** for now.

**Comment by 3LucasZ** [comment]
Yes, as mentioned in the comment:
'"Blocked" function is not implemented yet (it's basically detect current spike task that will be done by someone else)'
