### ISSUE TITLE
Dampen PivotSetAngle

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/FRC_Programming_2024#139]
Copy the `PivotSetAngle` command (branch from testing-2-6-24), and rewrite it to instead of using a PIDController, use a ProfiledPIDController to dampen the PivotSetAngle as we get closer to the setpoint.

**Comment by ChaoticChaosTheGreat** [comment]
Pivot set angle I don't think uses pid command anymore.Instead it uses the talon fx pid controller. This can easily be done with Motion Magic which should not take long to implement since PID is already tuned.

**Comment by ChaoticChaosTheGreat** [comment]
Needs to be tested but is implemented already.
