### ISSUE TITLE
AdvKit: Setup simulation / "replays"

### ISSUE THREAD

**Issue by ThatXliner** [Team3256/FRC_Programming_2024#21]
AdvantageKit can "replay" logs into subsystems and commands, so that you can test without having a real robot.
Your deliverable for this will include a document detailing how a software member can use a replay file to test things. The more visuals, the better.

Useful links:
https://github.com/Mechanical-Advantage/AdvantageKit/blob/main/docs/WHAT-IS-ADVANTAGEKIT.md#example-1-output-logging-in-replay

https://github.com/Mechanical-Advantage/AdvantageKit/blob/main/docs/WHAT-IS-ADVANTAGEKIT.md#example-1-output-logging-in-replay

**Comment by ThatXliner** [comment]
Ok so I read the documentation on it, and the status on this issue is that I'm unable to write such a document without trying it first. This means that we need real sensor data to be able to replay in sim

**Comment by ThatXliner** [comment]
- Blocked by #5
 - Blocked by #15

**Comment by ThatXliner** [comment]
Now I just need some AdvKit data to try on

**Comment by 3LucasZ** [comment]
Not using AdvKit
