### ISSUE TITLE
Phoenix6 Swerve

### ISSUE THREAD

**Issue by memori034** [Team3256/FRC_Programming_2024#32]
Update kinematics, tune PID in SwerveConstants, implement feedforward

**Comment by realjoshuau** [comment]
PERSONA 6????

**Comment by ChaoticChaosTheGreat** [comment]
duplicate of advanced swerve features?

**Comment by memori034** [comment]
phenix6 implementation

**Comment by memori034** [comment]
@realjoshuau is feat/swerve redundant now

**Comment by memori034** [comment]
implement azimuth, simulationPeriodic
