### ISSUE TITLE
Add AdvantageKit to Swerve Sim

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/FRC_Programming_2024#5]
[still working on adding issue description]

**Comment by DragonXDev** [comment]
https://github.com/Mechanical-Advantage/AdvantageKit/releases/tag/v3.0.0-beta-6

Latest version of AdvantageKit is not compatible with WPILib 2024

**Comment by ThatXliner** [comment]
Blocked as AdvantageKit hasn't updated yet

**Comment by ChaoticChaosTheGreat** [comment]
unblocked woohoo

**Comment by DragonXDev** [comment]
Currently we will implement AdvantageKit to the Swerve Sim for testing purposes, but implement it for the real Swerve subsystem later.
