### ISSUE TITLE
Motion Magic all the things

### ISSUE THREAD

**Issue by realjoshuau** [Team3256/FRC_Programming_2024#74]
https://v6.docs.ctr-electronics.com/en/stable/docs/api-reference/device-specific/talonfx/motion-magic.html

- [x] Climb: MM Position
- [ ] Arm: MM Position (?)
- [x] Intake:  MM Voltage? research
- [x] Shooter: MM Velocity

**Comment by realjoshuau** [comment]
MM should be an optional mode, use a feature flag

**Comment by ChaoticChaosTheGreat** [comment]
I don't think there is a such thing called MM voltage, because if you think about it that makes no sense. But motion magic velocity and position seem easy integrate.

**Comment by realjoshuau** [comment]
Yeah, I meant velocity

**Comment by DragonXDev** [comment]
Blocked by #26

**Comment by ChaoticChaosTheGreat** [comment]
closed because arm subsystem dont use talonfx pid
