### ISSUE TITLE
Choreo Autos (Outdated: See Autos)

### ISSUE THREAD

**Issue by memori034** [Team3256/FRC_Programming_2024#88]
Optimize existing autos with Choreo

**Comment by memori034** [comment]
Start with the highest scoring / most complex autos first. Lower level autos such as mobility will likely not be optimized, only if a full migration to Choreo from Pathplanner4 is required

**Comment by memori034** [comment]
Choreo used as a trajectory supplement for pathplanner. All autos will be pathplanner autos. But those with Choreo implementation will follow the this issue's scheme: highest autos will be fully implemented first, and lowest ones will remain fully pathplanner

**Comment by 3LucasZ** [comment]
I agree with you Sam. Good call. We should keep this closed for now.
